NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 10;
NDefines.NProduction.RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 10;
NDefines.NProduction.LICENSE_EQUIPMENT_BASE_SPEED = -0.2;

NDefines.NDiplomacy.TRUCE_PERIOD_AFTER_KICKING_FROM_FACTION = 30;
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 20;
NDefines.NDiplomacy.TENSION_LIBERATE = -2.5;
NDefines.NDiplomacy.BASE_CONDITIONAL_PEACE_WARSCORE_RATIO = 0.25;
NDefines.NDiplomacy.BASE_CONDITIONAL_PEACE_MONTHS = 2;
NDefines.NDiplomacy.PEACE_SCORE_DISTRIBUTION = { 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15 };
NDefines.NDiplomacy.PEACE_CONTEST_REFUND_FACTOR = { 1.0, 0.95, 0.90, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.5 };
NDefines.NDiplomacy.EMBARGO_COST = 50;
NDefines.NDiplomacy.EMBARGO_THREAT_THRESHOLD = 1;
NDefines.NDiplomacy.AIR_SUPPLY_CONVERSION_SCALE = 0.005;
NDefines.NDiplomacy.PEACE_COST_FACTOR_CAPITAL_SHIP_IC = 0.001;
NDefines.NDiplomacy.PEACE_COST_FACTOR_SCREENING_SHIP_IC = 0.001;
NDefines.NDiplomacy.ASSUME_FACTION_LEADERSHIP_PP_COST = 150;
NDefines.NDiplomacy.PEACE_TIMED_EFFECT_LENGTH_WAR_REPARATION = 3650;
NDefines.NDiplomacy.PEACE_TIMED_EFFECT_LENGTH_RESOURCE_RIGHTS = 3650;
NDefines.NDiplomacy.PEACE_COST_FACTOR_UNCONTESTED_BID_STEP = 0.1;
NDefines.NDiplomacy.PEACE_INCREASE_COST_FACTOR_PER_MISSING_PERCENT_FOR_CAPITULATION = 0.001;
NDefines.NDiplomacy.PEACE_SCORE_SCALE_FACTOR = 1.3;
NDefines.NDiplomacy.PEACE_ACTION_MAX_COST = 8000;
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_ANNEX = 250;
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_FREE = 250;
			
NDefines.NCountry.INDUSTRY_SCORE_MULTIPLIER = 1.25;
NDefines.NCountry.AIR_SCORE_MULTIPLIER = 0.08;
NDefines.NCountry.POLITICAL_POWER_UPPER_CAP = 1500.0;
NDefines.NCountry.POLITICAL_POWER_LOWER_CAP = -300.0;
NDefines.NCountry.STATE_VALUE_BUILDING_SLOTS_MULT = 5.0;
NDefines.NCountry.STATE_VALUE_BASE = 5.0;
		
NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 25;
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 70;
NDefines.NGame.GAME_SPEED_SECONDS = { 0.5, 0.25, 0.1, 0.05, 0.0 };

NDefines.NTechnology.LICENSE_PRODUCTION_TECH_BONUS = 0.25;
NDefines.NTechnology.USE_BONUS_REGRET_TIMER = 7;

NDefines.NMilitary.NUKE_DELAY_HOURS = 16;
NDefines.NMilitary.WAR_SCORE_LOSSES_RATIO = 0.45;
NDefines.NMilitary.WAR_SCORE_STRATEGIC_BOMBING_FACTOR = 0.025;
NDefines.NMilitary.WAR_SCORE_AIR_IC_LOSS_FACTOR = 0.075;
NDefines.NMilitary.WAR_SCORE_PROVINCE_FACTOR = 3.75;							
NDefines.NMilitary.WAR_SCORE_LEND_LEASE_RECEIVED_IC_FACTOR = 0.001; 			
NDefines.NMilitary.WAR_SCORE_LEND_LEASE_RECEIVED_FUEL_FACTOR = 0.001; 	
NDefines.NMilitary.PIERCING_THRESHOLDS = {
		1.00,
		0.80,
		0.60,
		0.40,
		0.20,
		0.00,
	};
NDefines.NMilitary.PIERCING_THRESHOLD_DAMAGE_VALUES = {
		1.00,
		0.85,
		0.75,
		0.65,
		0.55,
		0.45,
	};	

NDefines.NOperatives.MAX_OPERATIVE_SLOT_FROM_AGENCY_UPGRADES = 2;
NDefines.NOperatives.AGENCY_OPERATIVE_RECRUITMENT_TIME = 20;
NDefines.NOperatives.OPERATIVE_MAX_DAYS_HARMED = 100;
NDefines.NOperatives.OPERATIVE_MAX_DAYS_FORCED_INTO_HIDING = 100;

NDefines.NNavy.WAR_SCORE_DECAY_FOR_BUILT_CONVOY = 0.025;

NDefines.NIntel.INTEL_NETWORK_MAX_CIVILIAN_INTEL = 25.0;
NDefines.NIntel.CIVILIAN_MANPOWER_RANGE_INTEL_MAX = 0.6;

NDefines.NAI.PEACE_BID_FOLD_AGAINST_PLAYER_CHANCE = 1;


